#ifndef SDL_CUSTOM_H_INCLUDED
#define SDL_CUSTOM_H_INCLUDED

enum
{
    SDL_TICK   = SDL_USEREVENT + 0,
    SDL_INIT   = SDL_USEREVENT + 1,
    SDL_REDRAW = SDL_USEREVENT + 2,
};

#endif // SDL_CUSTOM_H_INCLUDED
